### PR TITLE
FungibleToken Factory Manager Setup Transaction

### PR DESCRIPTION
**Pull request by sisyphusSmiling**
Closes: #151

### CODE REVIEW

**Comment by austinkline** [comment]
Nice to see this one! It looks like we ended up adding some other types for to our flowty-maintained testnet resource
https://f.dnz.dev/0x5617ff347e16bd72/storage/CapabilityFactory_0x294e44e1ec6993c6

Are we missing factories for some of these types? I'll look around at standard contracts to see if the missing combinations are generally in use

**Comment by sisyphusSmiling** [comment]
Looks like there's a contract [`FTFactories`](https://f.dnz.dev/0xf57b085a64c8ab02/FTFactories) defining a number of FT-related factory implementations. The addition to the hosted `Manager` you linked looks to be a `{Receiver, Balance}` Capability.

I do like consolidating the factories into a single contract, but kinda late into the game to switch up the pattern. What do you think about deploying another contract defining such a Factory?

**Comment by austinkline** [comment]
> I do like consolidating the factories into a single contract, but kinda late into the game to switch up the pattern. What do you think about deploying another contract defining such a Factory?

Yeah... I didn't even think to consolidate them until I needed something for testing and threw it all together 🙁 I think it's totally fine to stick with how we're doing it and make a new contract. They're tiny, which means it's easy for a reader to understand exactly what it's for

**Review by joshuahannan — APPROVED** [review]
have a test for this somewhere?

**Comment by sisyphusSmiling** [comment]
Good callout @joshuahannan I'll add test cases

**Review by joshuahannan — APPROVED** [review]

**Pull request merged**
